####################################################
### MS
####################################################
quarkus.http.port=8081

####################################################
### DATASOURCE
####################################################
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=Oracle123
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

####################################################
### HIBERNATE ORM
####################################################
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.jdbc.statement-fetch-size=50

####################################################
### OPENAPI / SWAGGER UI
####################################################
quarkus.smallrye-openapi.info-title=Employee Microservice API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=REST API for employee management following hexagonal architecture
quarkus.smallrye-openapi.info-contact-name=Jorge MCS
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

####################################################
### HEALTH CHECKS
####################################################
quarkus.smallrye-health.ui.always-include=true
quarkus.smallrye-health.liveness-path=/health/live
quarkus.smallrye-health.readiness-path=/health/ready
quarkus.smallrye-health.root-path=/health

####################################################
### LOGGING
####################################################
#quarkus.log.level=INFO
#quarkus.log.min-level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.console.level=INFO
quarkus.log.console.stderr=false
quarkus.log.console.darken=0
quarkus.log.category."com.jmacse.ms".level=DEBUG



